### ISSUE TITLE
Local Setup Error - supabase is required

### ISSUE THREAD

**Issue by AmirNaghibi** [stockanalysisdev/stock-analysis#233]
**What is the issue?**
After I followed the instruction in readme, I got an error `supabase is required` 

**What page was it on?**
localhost:3001

**More**
I have solved the issue by creating a free supabase account and copying URL and anonymous key in a **.env** file.

**If you allow me, I would love to open a PR updating the README.md**

Great project by the way 💯 Would love to contribute more and provide value 😃

**Comment by kristjanmar** [comment]
Hey Amir,

Thanks a lot for pointing this out, I just double checked to confirm and you are right.

Yes, if you open the PR then I would love to add this to the instructions. And if you are interested in working on anything else then it will be highly appreciated 🙂

Best,
Kris

**Comment by kristjanmar** [comment]
Thanks a lot! I have merged the changes, although I modified the text a little.

**Comment by AmirNaghibi** [comment]
Thanks @kristjanmar !
Are there any other environment variables that are needed for development in **.env** file? 

The **Chart** tab is not loading. I can open a new issue to investigate. 


https://user-images.githubusercontent.com/20001191/151675251-c641e138-5979-4b10-adc4-0b9e4dfbc0fe.mov

**Comment by kristjanmar** [comment]
Hey Amir,

Try adding this line to the .env file, it should fix it:

NEXT_PUBLIC_API_URL=https://api.stockanalysis.com/wp-json/sa

**Comment by AmirNaghibi** [comment]
Amazing! worked 💯
